// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6H8B-p0hKxJwOwkbboN-eVOOZx1dSUX0',
    appId: '1:1095509510125:android:5617ffe073cb0b3ec549e4',
    messagingSenderId: '1095509510125',
    projectId: 'habit-tracker-cd94a',
    databaseURL: 'https://habit-tracker-cd94a-default-rtdb.firebaseio.com',
    storageBucket: 'habit-tracker-cd94a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAt8cVN4oMqRHe1KVapWybqQYSidWGboE',
    appId: '1:1095509510125:ios:edc6458bc0e59f55c549e4',
    messagingSenderId: '1095509510125',
    projectId: 'habit-tracker-cd94a',
    databaseURL: 'https://habit-tracker-cd94a-default-rtdb.firebaseio.com',
    storageBucket: 'habit-tracker-cd94a.appspot.com',
    iosBundleId: 'com.example.habitTrackerApp',
  );
}
